const FETCHING_PRODUCT = "FETCHING_PRODUCT";
const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";

export { FETCHING_PRODUCT, ADD_PRODUCT_TO_CART, REMOVE_PRODUCT_FROM_CART };
